services:
  temperature-blanket-ui:
    build:
      context: ./
    depends_on:
      - temperature-blanket-gql
    environment:
      NODE_ENV: production
    ports:
      - "9000:8080"

  temperature-blanket-gql:
    build:
      context: ./backend/
    env_file:
      - ./backend/.env
    ports:
      - "9001:9001"
