# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as two services called "todo-app" and “todo-database”
# You can add other services your application may depend on here.

services:
  temperature-blanket-ui:
    build:
      context: ./
    depends_on:
      - temperature-blanket-gql
    environment:
      NODE_ENV: production
    ports:
      - "9000:8080"

  temperature-blanket-gql:
    build:
      context: ./backend/
    environment:
      NODE_ENV: production

  #volumes:
  #database:
