services:
  temperature-blanket-ui:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - temperature-blanket-gql
    environment:
      NODE_ENV: production
    ports:
      - "9012:8080"
    networks:
      - app-network

  temperature-blanket-gql:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "9013:8080"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
